# Generated by Django 3.2 on 2024-01-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rhagencia',
            fields=[
                ('agecod', models.IntegerField(primary_key=True, serialize=False)),
                ('agenom', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rhagencia',
            },
        ),
        migrations.CreateModel(
            name='Rhempleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres de Empleados', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos Empleado', max_length=100)),
                ('agecod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rhagencia')),
            ],
            options={
                'verbose_name_plural': 'rhempleados',
                'unique_together': {('agecod', 'nombres')},
            },
        ),
    ]
