# Generated by Django 3.2 on 2024-02-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rhagencia',
            fields=[
                ('agecod', models.IntegerField(primary_key=True, serialize=False)),
                ('agenom', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rhagencia',
                'db_table': 'core_Rhagencia',
            },
        ),
        migrations.CreateModel(
            name='Rhmotiv',
            fields=[
                ('codmot', models.IntegerField(help_text='Id del motivo', primary_key=True, serialize=False, unique=True)),
                ('nommot', models.CharField(help_text='Descripcion de Motivo', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Rhmotiv',
                'db_table': 'core_Rhmotiv',
                'unique_together': {('codmot', 'nommot')},
            },
        ),
        migrations.CreateModel(
            name='Rhempleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres de Empleados', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos Empleado', max_length=100)),
                ('agecod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rhagencia')),
            ],
            options={
                'verbose_name_plural': 'rhempleados',
                'db_table': 'core_rhempleado',
                'unique_together': {('agecod', 'nombres')},
            },
        ),
        migrations.CreateModel(
            name='rhacademico',
            fields=[
                ('cod_academico', models.AutoField(help_text='Id del academico', primary_key=True, serialize=False, unique=True)),
                ('desc_academicos', models.IntegerField(default=0, help_text='Descripcion de grado Academico', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'rhacademico',
                'db_table': 'core_rhacademico',
                'unique_together': {('cod_academico', 'desc_academicos')},
            },
        )
    ]
