# Generated by Django 3.2 on 2024-02-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [

        migrations.RenameField(
            model_name='rhacademico',
            old_name='desc_academicos',
            new_name='desc_academico',
        ),
        migrations.AlterUniqueTogether(
            name='rhacademico',
            unique_together={('cod_academico', 'desc_academico')},
        ),
    ]
