# Generated by Django 3.2 on 2024-01-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhagencia',
            name='direccion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
