# Generated by Django 3.2 on 2024-01-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_rhagencia_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rhmotiv',
            fields=[
                ('codmot', models.IntegerField(primary_key=True, serialize=False)),
                ('nommot', models.CharField(help_text='Nombres de Empleados', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Rhmotiv',
                'unique_together': {('codmot', 'nommot')},
            },
        ),
    ]
