# Generated by Django 3.2 on 2024-02-05 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20240205_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rhacademico',
            old_name='desc_academico',
            new_name='desc_academicod',
        ),
        migrations.AlterUniqueTogether(
            name='rhacademico',
            unique_together={('cod_academico', 'desc_academicod')},
        ),
    ]
