# Generated by Django 3.2 on 2024-02-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20240205_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhacademico',
            name='desc_academicod',
            field=models.CharField(default=0, help_text='Descripcion de grado Academico', max_length=2),
        ),
    ]
