# Generated by Django 3.2 on 2024-01-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_rhmotiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhmotiv',
            name='codmot',
            field=models.IntegerField(help_text='Id del motivo', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rhmotiv',
            name='nommot',
            field=models.CharField(help_text='Descripcion de Motivo', max_length=100),
        ),
    ]
