# Generated by Django 3.2 on 2024-02-06 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20240206_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rhacademico',
            name='desc_academicod',
        ),
    ]
